"""
Email Output Plug for Aegis-1

Email notifications for buy/sell signals.
Based on PRD Section 5 - Output Plug 02: Email Output.
"""

import asyncio
import logging
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Any, Optional

import aiosmtplib

from outputs.base import BaseOutput, OutputStatus, OutputPriority
from models.signals import Signal, SignalAction
from db.redis_client import get_redis_client
from config.settings import settings


logger = logging.getLogger(__name__)


class EmailOutput(BaseOutput):
    """
    Email output plug for signal notifications.
    
    From PRD:
    - Requirement: Email notifications for buy/sell signals with formatted reports
    - Pattern: Configurable email templates with placeholders for signal data
    - Recipients: Support for multiple recipients, distribution lists, and 
      conditional routing
    - Format: HTML and plain-text email formats
    - Rate Limiting: Maximum 10 emails per hour per recipient. Critical signals 
      (confidence >0.9) bypass rate limiting.
    """
    
    # HTML email template
    HTML_TEMPLATE = """
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 0; padding: 20px; }}
            .header {{ background: {header_color}; color: white; padding: 20px; border-radius: 5px; }}
            .content {{ padding: 20px; background: #f9f9f9; margin-top: 10px; border-radius: 5px; }}
            .metric {{ display: inline-block; margin: 10px 20px 10px 0; }}
            .metric-label {{ font-size: 12px; color: #666; }}
            .metric-value {{ font-size: 24px; font-weight: bold; }}
            .reasoning {{ background: white; padding: 15px; margin-top: 15px; border-left: 4px solid {header_color}; }}
            .footer {{ margin-top: 20px; font-size: 12px; color: #666; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🚨 Trading Signal: {action}</h1>
            <p>{symbol} - {timestamp}</p>
        </div>
        <div class="content">
            <div class="metric">
                <div class="metric-label">Action</div>
                <div class="metric-value">{action}</div>
            </div>
            <div class="metric">
                <div class="metric-label">Confidence</div>
                <div class="metric-value">{confidence}%</div>
            </div>
            <div class="metric">
                <div class="metric-label">Position Size</div>
                <div class="metric-value">{position_size}%</div>
            </div>
            <div class="metric">
                <div class="metric-label">Risk Score</div>
                <div class="metric-value">{risk_score}</div>
            </div>
            <div class="reasoning">
                <strong>Reasoning:</strong><br>
                {reasoning}
            </div>
            <div class="reasoning">
                <strong>Plug Contributions:</strong><br>
                {plug_breakdown}
            </div>
        </div>
        <div class="footer">
            <p>Signal ID: {signal_id}</p>
            <p>Risk Decision: {risk_decision}</p>
            <p>Generated by Aegis-1 Trading System</p>
        </div>
    </body>
    </html>
    """
    
    # Plain text template
    TEXT_TEMPLATE = """
    TRADING SIGNAL: {action}
    =====================
    Symbol: {symbol}
    Time: {timestamp}
    
    METRICS
    -------
    Confidence: {confidence}%
    Position Size: {position_size}%
    Risk Score: {risk_score}
    Risk Decision: {risk_decision}
    
    REASONING
    ---------
    {reasoning}
    
    PLUG CONTRIBUTIONS
    ------------------
    {plug_breakdown}
    
    ---
    Signal ID: {signal_id}
    Generated by Aegis-1 Trading System
    """
    
    def __init__(
        self,
        output_id: str = "email",
        recipients: list[str] = None,
        smtp_host: str = None,
        smtp_port: int = None,
        smtp_user: str = None,
        smtp_password: str = None,
        from_address: str = None,
        rate_limit: int = None
    ):
        """
        Initialize Email output.
        
        Args:
            output_id: Unique identifier
            recipients: List of email recipients
            smtp_host: SMTP server host
            smtp_port: SMTP server port
            smtp_user: SMTP username
            smtp_password: SMTP password
            from_address: Sender email address
            rate_limit: Max emails per hour per recipient
        """
        super().__init__(output_id)
        
        self.recipients = recipients or []
        self.smtp_host = smtp_host or settings.smtp_host
        self.smtp_port = smtp_port or settings.smtp_port
        self.smtp_user = smtp_user or settings.smtp_user
        self.smtp_password = smtp_password or settings.smtp_password
        self.from_address = from_address or settings.email_from
        self.rate_limit = rate_limit or settings.email_rate_limit
        
        self._redis = None
    
    async def initialize(self) -> None:
        """Initialize email output."""
        self._redis = get_redis_client()
        self.status = OutputStatus.ACTIVE
        logger.info(f"Email output initialized with {len(self.recipients)} recipients")
    
    async def shutdown(self) -> None:
        """Shutdown email output."""
        self.status = OutputStatus.INACTIVE
        logger.info("Email output shutdown")
    
    async def send(self, signal: Signal) -> bool:
        """
        Send signal via email.
        
        Args:
            signal: Signal to send
        
        Returns:
            True if at least one email was sent successfully
        """
        if not self.recipients:
            logger.warning("No email recipients configured")
            return False
        
        if not self.smtp_user or not self.smtp_password:
            logger.warning("SMTP credentials not configured")
            return False
        
        # Build email content
        html_content = self._build_html(signal)
        text_content = self._build_text(signal)
        
        success_count = 0
        
        for recipient in self.recipients:
            # Check rate limit (bypass for critical signals)
            if not signal.is_critical:
                if not await self._check_rate_limit(recipient):
                    logger.info(f"Rate limited for {recipient}, skipping")
                    continue
            
            try:
                message = self._build_message(
                    signal, recipient, html_content, text_content
                )
                
                await aiosmtplib.send(
                    message,
                    hostname=self.smtp_host,
                    port=self.smtp_port,
                    username=self.smtp_user,
                    password=self.smtp_password,
                    start_tls=True
                )
                
                success_count += 1
                logger.info(f"Email sent to {recipient} for signal {signal.id}")
                
            except Exception as e:
                logger.error(f"Failed to send email to {recipient}: {e}")
        
        return success_count > 0
    
    def _build_message(
        self,
        signal: Signal,
        recipient: str,
        html_content: str,
        text_content: str
    ) -> MIMEMultipart:
        """Build MIME message."""
        message = MIMEMultipart("alternative")
        
        # Subject
        action_emoji = "🟢" if signal.action == SignalAction.BUY else "🔴" if signal.action == SignalAction.SELL else "⚪"
        message["Subject"] = f"{action_emoji} Aegis Signal: {signal.action.value} {signal.symbol}"
        message["From"] = self.from_address
        message["To"] = recipient
        
        # Attach both plain text and HTML
        message.attach(MIMEText(text_content, "plain"))
        message.attach(MIMEText(html_content, "html"))
        
        return message
    
    def _build_html(self, signal: Signal) -> str:
        """Build HTML email content."""
        # Color based on action
        if signal.action == SignalAction.BUY:
            header_color = "#28a745"  # Green
        elif signal.action == SignalAction.SELL:
            header_color = "#dc3545"  # Red
        else:
            header_color = "#6c757d"  # Gray
        
        # Build plug breakdown
        plug_lines = []
        for plug_id, contrib in signal.plug_contributions.items():
            direction = contrib.get("direction", 0)
            confidence = contrib.get("confidence", 0)
            plug_lines.append(
                f"{plug_id}: direction={direction:+.2f}, confidence={confidence:.1%}"
            )
        plug_breakdown = "<br>".join(plug_lines) if plug_lines else "N/A"
        
        return self.HTML_TEMPLATE.format(
            header_color=header_color,
            action=signal.action.value,
            symbol=signal.symbol,
            timestamp=signal.timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"),
            confidence=f"{signal.confidence * 100:.1f}",
            position_size=f"{signal.position_size * 100:.2f}",
            risk_score=f"{signal.risk_score:.2f}",
            reasoning=signal.reasoning,
            plug_breakdown=plug_breakdown,
            signal_id=str(signal.id),
            risk_decision=signal.risk_decision.value
        )
    
    def _build_text(self, signal: Signal) -> str:
        """Build plain text email content."""
        # Build plug breakdown
        plug_lines = []
        for plug_id, contrib in signal.plug_contributions.items():
            direction = contrib.get("direction", 0)
            confidence = contrib.get("confidence", 0)
            plug_lines.append(
                f"  {plug_id}: direction={direction:+.2f}, confidence={confidence:.1%}"
            )
        plug_breakdown = "\n".join(plug_lines) if plug_lines else "  N/A"
        
        return self.TEXT_TEMPLATE.format(
            action=signal.action.value,
            symbol=signal.symbol,
            timestamp=signal.timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"),
            confidence=f"{signal.confidence * 100:.1f}",
            position_size=f"{signal.position_size * 100:.2f}",
            risk_score=f"{signal.risk_score:.2f}",
            reasoning=signal.reasoning,
            plug_breakdown=plug_breakdown,
            signal_id=str(signal.id),
            risk_decision=signal.risk_decision.value
        )
    
    async def _check_rate_limit(self, recipient: str) -> bool:
        """
        Check if recipient is rate limited.
        
        From PRD: Maximum 10 emails per hour per recipient.
        Critical signals (confidence >0.9) bypass rate limiting.
        
        Returns:
            True if email can be sent, False if rate limited
        """
        if not self._redis:
            return True
        
        key = f"email:{recipient}"
        return await self._redis.check_rate_limit(
            key,
            max_requests=self.rate_limit,
            window_seconds=3600  # 1 hour
        )
    
    def add_recipient(self, email: str) -> None:
        """Add email recipient."""
        if email not in self.recipients:
            self.recipients.append(email)
    
    def remove_recipient(self, email: str) -> None:
        """Remove email recipient."""
        if email in self.recipients:
            self.recipients.remove(email)
